### PR TITLE
feat(android): update firebase to latest

### PR DESCRIPTION
**Pull request by hansemannn**
Working! Keeping this open until verified by other community members.

Prerelease: [firebase.core-android-4.0.0.zip](https://github.com/hansemannn/titanium-firebase-core/files/2999356/firebase.core-android-4.0.0.zip)

### CODE REVIEW

**Comment by m1ga** [comment]
add firebase-common and firebase-iid to remove those errors

**Comment by hansemannn** [comment]
They don't exist anymore in latest Firebase

**Comment by m1ga** [comment]
I'm not exactly sure how the version systems works 😄 
https://firebase.google.com/support/release-notes/android
core is 16.0.7, messaging is 17.3.4. So common would be https://mvnrepository.com/artifact/com.google.firebase/firebase-common/16.0.4 and https://mvnrepository.com/artifact/com.google.firebase/firebase-iid 16.0.0 (or the 17.0.4)? Not sure 🤔

I'll try to setup a Android Firebase project and check which versions it will include.

**Comment by hansemannn** [comment]
Oh thats weird. On the Firebase homepage, those are not listed anymore. But if the latest ones are available, they should indeed be tested.

*EDIT*: I've added them and the build succeeds now. I added a release above. To build the other modules, make sure to expand the `firebase.core` one in the Ti `Application Support` directory (`~/Library/Application Support/Titanium/modules/android/firebase.core/4.0.0`) so it can be used as a build dependency.

**Comment by fahad86** [comment]
please use the latest lib for play-services-measurement-base: https://mvnrepository.com/artifact/com.google.android.gms/play-services-measurement-base/16.3.0

please also include https://mvnrepository.com/artifact/com.google.firebase/firebase-iid-interop/16.0.1 as I got a class not found: com.google.firebase.iid.internal.FirebaseInstanceIdInternal

**Comment by hansemannn** [comment]
@fahad86 All play-services are based on [Ti.PlayServices](https://github.com/appcelerator-modules/ti.playservices) which was just updated to latest (see releases [here](https://github.com/appcelerator-modules/ti.playservices/releases). But it seems like it's already a bit outdated?

**Comment by fahad86** [comment]
,Sent from my Samsung Galaxy smartphone.e5*
null

**Comment by hansemannn** [comment]
@fahad86 thx!

**Comment by fahad86** [comment]
> please use the latest lib for play-services-measurement-base: https://mvnrepository.com/artifact/com.google.android.gms/play-services-measurement-base/16.3.0
> 
> please also include https://mvnrepository.com/artifact/com.google.firebase/firebase-iid-interop/16.0.1 as I got a class not found: com.google.firebase.iid.internal.FirebaseInstanceIdInternal

sorry the first part of this comment was meant to be on your ti.playservices module latest dist :)

**Comment by hansemannn** [comment]
Alright. Can you do a pull request on Ti.PlayServices to add the new library versions?

**Comment by Wingee** [comment]
I've tried 4.0.0 but I'm getting the following error

`03-12 11:26:52.055 14353 14353 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/internal/FirebaseInstanceIdInternal;
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at com.google.firebase.iid.Registrar.getComponents(Unknown Source)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at com.google.firebase.components.ComponentRuntime.<init>(com.google.firebase:firebase-common@@16.0.4:52)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.<init>(com.google.firebase:firebase-common@@16.0.4:539)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.0.4:355)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.0.4:324)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.0.4:310)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@16.0.4:53)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1759)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1734)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@16.0.4:47)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6420)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6012)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5951)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.internal.FirebaseInstanceIdInternal" on path: DexPathList[[zip file "/data/app/com.ingelby.grititranger-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ingelby.grititranger-1/lib/arm, /data/app/com.ingelby.grititranger-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-12 11:26:52.055 14353 14353 E AndroidRuntime: 	... 21 more`

**Comment by hansemannn** [comment]
@Wingee Please read the above comments more carefully. It clearly states that it's wip.

**Comment by hansemannn** [comment]
@m1ga @Wingee @hansemannn PR updated!

**Comment by Wingee** [comment]
Amazing thanks!

**Pull request merged**
