### PR TITLE
fix(android): Update firebase-core

### PR DESCRIPTION
**Pull request by m1ga**
* update to com.google.firebase:firebase-core:18.0.1

will get rid of the warning:
```
[WARN]  ConnectionTracker: Exception thrown while unbinding
[WARN]  ConnectionTracker: java.lang.IllegalArgumentException: Service not registered: ls@26fb575
[WARN]  ConnectionTracker:      at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1781)
[WARN]  ConnectionTracker:      at android.app.ContextImpl.unbindService(ContextImpl.java:1874)
[WARN]  ConnectionTracker:      at android.content.ContextWrapper.unbindService(ContextWrapper.java:792)
[WARN]  ConnectionTracker:      at ci.f(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):1)
[WARN]  ConnectionTracker:      at ci.d(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):2)
[WARN]  ConnectionTracker:      at lt.E(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):9)
[WARN]  ConnectionTracker:      at ld.a(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):3)
[WARN]  ConnectionTracker:      at ef.run(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):3)
[WARN]  ConnectionTracker:      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
[WARN]  ConnectionTracker:      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[WARN]  ConnectionTracker:      at iy.run(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):5)
```
[firebase.core-android-6.1.1.zip](https://github.com/hansemannn/titanium-firebase-core/files/5860675/firebase.core-android-6.1.1.zip)

### CODE REVIEW

**Comment by hansemannn** [comment]
Nice! Ready to merge already?

**Comment by m1ga** [comment]
yes, was doing a lot of tests yesterday (trying to implement groups) and didn't see that error popping up :smile:

**Review by hansemannn — APPROVED** [review]

**Comment by hansemannn** [comment]
Thx! Wondering, when we should update play services as well. Which one do you currently use / recommend?

**Comment by m1ga** [comment]
think https://github.com/appcelerator-modules/ti.playservices/blob/master/android/build.gradle is still the latest when I search for the includes at https://developers.google.com/android/guides/releases

**Pull request merged**
