### PR TITLE
Android: Update dependencies

### PR DESCRIPTION
**Pull request by m1ga**
Update dependencies:
* com.google.firebase:firebase-core: 18.0.0

### CODE REVIEW

**Comment by hansemannn** [comment]
Any notable features that we can add?

**Comment by m1ga** [comment]
Doesn't look like it. Not sure what the firebase-common update does but it is only a 0.0.1 one.

**IID changelog:**

* 20.2.3: internal
* 20.2.2: internal improvments (don't use)
* 20.2.1: Removed calls to getResourceAsStream because it was causing a performance bottleneck.
* 20.2.0:	internal
* 20.1.7:	Further improved the detection of invalid FirebaseOptions
* 20.1.6:	Further improved the detection of invalid FirebaseOptions
* 20.1.5:	internal
* 20.1.3:	Tokens are now scoped to their respective FirebaseApp instance. Apps that instantiate multiple FirebaseApp instances will now see a different token for each app.
		FirebaseApp now requires a non-empty project ID set in the corresponding FirebaseOptions.
* 20.1.2:	internal
* 20.1.1:	Fixed a bug that was causing silent failures in apps that use the deprecated FirebaseInstanceId#getToken() method without providing the required values for FirebaseOptions
* 20.1.0:	(don't use) Firebase Instance ID now depends on the Firebase installations SDK

https://firebase.google.com/support/release-notes/android#iid_v20-2-3
and search for "Firebase Instance ID version" to find all changes :)

**Comment by m1ga** [comment]
@hansemannn: done, please test it, then it is ready to be released

**Comment by hansemannn** [comment]
I currently dont have much capacity to test. If someone can jump in to validate common scenarios, I'd appreciate it!

**Comment by hansemannn** [comment]
@m1ga Can you try to use BoM here? Then, if this is working and merged, we can move all others to a version-stable Firebase environment as well.
```gradle
implementation'com.google.firebase:firebase-bom:25.12.0'

implementation 'com.google.firebase:firebase-iid'
implementation 'com.google.firebase:firebase-common'
```
This way, we only have to maintain the BoM version in each repo and it will find the latest matching version for itself. Reference: https://firebase.google.com/docs/android/setup#firebase-bom

**Comment by m1ga** [comment]
@hansemannn I'll test that. Looks easier to maintain!

**Comment by m1ga** [comment]
@hansemannn it "works" but you'll have to add
```
dependencies {
	implementation platform('com.google.firebase:firebase-bom:25.12.0')
}
```
to the app build.gradle. Otherwise it will throw a gradle compile error. Updated the push module and tested both of them together. 

Is that something we can ask a user to add? Would add it to the `core` readme

**Comment by hansemannn** [comment]
Oh, really? I think it's okay! And (in theory) it could even allow users to hotpatch the BoM themselves, couldn't they? But lets definitely make sure to bump the major version and add a solid readme note.

**Comment by m1ga** [comment]
removed BoM see https://github.com/hansemannn/titanium-firebase-cloud-messaging/pull/115#issuecomment-716028881 for more info

Tests still work fine with this version and the FCM from the other PR

**Comment by m1ga** [comment]
* updated to a newer version
* tested it with 9.2.2 and 9.3.0 + ti.playservices 17.5.0 -> working fine (in combination with fcm)

[firebase.core-android-6.0.1.zip](https://github.com/hansemannn/titanium-firebase-core/files/5541236/firebase.core-android-6.0.1.zip)

**Comment by m1ga** [comment]
@hansemannn you can merge this too. Only tested this in combination with the new fcm

**Pull request merged**
